// Draws the Cassette app icon from the interface's own SVG mark.
//
// The mark lives in src/renderer/shared/icons: app.svg for everything from
// 32px up, and app-16.svg, drawn with a heavier stroke, for the two sizes
// where a 1.6 stroke would dissolve. Chromium does the rasterising, so the
// icon is exactly the SVG and the build needs no image toolchain beyond the
// Electron it already has.
//
// Writes build/icon.png (512), build/icon.ico (16–256) and build/logo.svg.
//
// Run: npx electron scripts/render-icon.cjs

const { app, BrowserWindow } = require('electron')
const { readFileSync, writeFileSync } = require('node:fs')
const { join } = require('node:path')

const root = join(__dirname, '..')
const icons = join(root, 'src', 'renderer', 'shared', 'icons')

// The interface's ink and brass, as hex because the .ico and the README
// outlive any stylesheet.
const INK = '#1c1a17'
const EDGE = '#3a352e'
const BRASS = '#d9a441'

/** The glyph's inner markup, without its own <svg> wrapper. */
function glyph(file) {
  const svg = readFileSync(join(icons, file), 'utf8')
  return svg.match(/<svg[^>]*>([\s\S]*)<\/svg>/)[1].trim()
}

/**
 * The icon at one size, as an SVG document.
 *
 * Small sizes give the glyph more of the tile: at 16px every pixel of stroke
 * counts, and a generous margin leaves nothing legible.
 */
function iconSvg(size) {
  const small = size <= 24
  const inner = glyph(small ? 'app-16.svg' : 'app.svg')
  const stroke = small ? 2 : 1.6
  // The tile, then the glyph scaled into it. 24 is the glyph's viewBox.
  const margin = small ? 0.02 : 0.14
  const scale = (1 - margin * 2) / 24
  const radius = small ? 0.18 : 0.22
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1 1" width="${size}" height="${size}">
  <rect x="0" y="0" width="1" height="1" rx="${radius}" fill="${INK}"/>
  ${small ? '' : `<rect x="0.006" y="0.006" width="0.988" height="0.988" rx="${radius - 0.006}" fill="none" stroke="${EDGE}" stroke-width="0.012"/>`}
  <g transform="translate(${margin} ${margin}) scale(${scale})" fill="none" stroke="${BRASS}"
     stroke-width="${stroke}" stroke-linecap="round" stroke-linejoin="round">${inner}</g>
</svg>`
}

async function rasterise(window, size) {
  const html = `<body style="margin:0;background:transparent">${iconSvg(size)}</body>`
  await window.loadURL('data:text/html;charset=utf-8,' + encodeURIComponent(html))
  // An offscreen window paints on its own schedule; capturing before the
  // first frame waits forever.
  await new Promise((resolve) => setTimeout(resolve, 300))
  const image = await window.webContents.capturePage({ x: 0, y: 0, width: size, height: size })
  return image.resize({ width: size, height: size }).toPNG()
}

/** An .ico whose entries are PNGs, which Windows has read since Vista. */
function ico(entries) {
  const header = Buffer.alloc(6)
  header.writeUInt16LE(0, 0)
  header.writeUInt16LE(1, 2)
  header.writeUInt16LE(entries.length, 4)
  const directory = Buffer.alloc(16 * entries.length)
  let offset = 6 + directory.length
  entries.forEach(({ size, png }, i) => {
    const at = i * 16
    directory.writeUInt8(size >= 256 ? 0 : size, at)
    directory.writeUInt8(size >= 256 ? 0 : size, at + 1)
    directory.writeUInt16LE(1, at + 4) // colour planes
    directory.writeUInt16LE(32, at + 6) // bits per pixel
    directory.writeUInt32LE(png.length, at + 8)
    directory.writeUInt32LE(offset, at + 12)
    offset += png.length
  })
  return Buffer.concat([header, directory, ...entries.map((e) => e.png)])
}

app.whenReady().then(async () => {
  const window = new BrowserWindow({
    show: false,
    width: 512,
    height: 512,
    transparent: true,
    frame: false,
    webPreferences: { offscreen: true }
  })
  // Offscreen rendering at a device scale of 1, so a 16px icon is 16 pixels.
  window.webContents.setZoomFactor(1)

  const sizes = [16, 24, 32, 48, 64, 128, 256]
  const entries = []
  for (const size of sizes) entries.push({ size, png: await rasterise(window, size) })

  const build = join(root, 'build')
  writeFileSync(join(build, 'icon.ico'), ico(entries))
  writeFileSync(join(build, 'icon.png'), await rasterise(window, 512))
  writeFileSync(
    join(build, 'logo.svg'),
    `<!--
  Cassette — app mark. Generated by scripts/render-icon.cjs from
  src/renderer/shared/icons/app.svg; edit that, not this.
-->
${iconSvg(512)}
`
  )
  console.log(`wrote build/icon.ico (${sizes.join(', ')}), build/icon.png, build/logo.svg`)
  app.quit()
})
